name: task-scheduler
services:
  api:
    build: .
    image: task-scheduler-api
    container_name: task-scheduler-api

    ports:
      - "5000:5000"

    env_file:
      - .env

    depends_on:
      - mongodb
      - rabbitmq

  worker:
    build: .
    image: task-scheduler-worker
    container_name: task-scheduler-worker

    command: npm run worker

    env_file:
      - .env

    depends_on:
      - mongodb
      - rabbitmq

  mongodb:
    image: mongo:8

    container_name: mongodb

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management

    container_name: rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongo-data: